name: taskverse
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.5.3
  cupertino_icons: ^1.0.2
  date_format: ^2.0.7
  flutter:
    sdk: flutter
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter_lints: ^2.0.0
  flutter_local_notifications: ^14.1.1
  flutter_modular: ^5.0.3
  flutter_native_timezone: ^2.0.0
  form_field_validator: ^1.1.0
  get: ^4.6.5
  google_fonts: ^4.0.4
  intl: ^0.17.0
  shared_preferences: ^2.1.0
  rxdart: ^0.27.7
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true
